'use strict'
var iter = require('./iterator'),
    transformer = require('./transformer'),
    protocols = {
      iterator: require('./iterator/symbol'),
      transformer: require('./transformer/symbol')
    }

module.exports = {
  reduce: require('./reduce'),
  transduce: require('./transduce'),
  into: require('./into'),
  toArray: require('./toarray'),
  map: require('./map'),
  filter: require('./filter'),
  remove: require('./remove'),
  take: require('./take'),
  takeWhile: require('./takewhile'),
  drop: require('./drop'),
  dropWhile: require('./dropwhile'),
  cat: require('./cat'),
  mapcat: require('./mapcat'),
  partitionAll: require('./partitionall'),
  partitionBy: require('./partitionby'),
  isIterable: iter.isIterable,
  isIterator: iter.isIterator,
  iterable: iter.iterable,
  iterator: iter.iterator,
  isTransformer: transformer.isTransformer,
  transformer: transformer.transformer,
  compose: require('./util/compose'),
  isReduced: require('./util/isReduced'),
  reduced: require('./util/reduced'),
  unreduced: require('./util/unreduced'),
  protocols: protocols,
  isFunction: require('./util/isFunction'),
  isArray: require('./util/isArray'),
  isString: require('./util/isString'),
  isRegExp: require('./util/isRegExp'),
  isNumber: require('./util/isNumber'),
  isUndefined: require('./util/isUndefined'),
  arrayPush: require('./util/arrayPush'),
  objectMerge: require('./util/objectMerge'),
  stringAppend: require('./util/stringAppend'),
  identity: require('./util/identity'),
}
